### ISSUE TITLE
Make sure to include all source code in your repository

### ISSUE THREAD

**Issue by michaelcfanning** [maximilianfanning/NameGenerator#1]
I only see specific files checked into this repo. Where is your Visual Studio solution file, for example? Also, if your code references other code, we want to make sure it's here. Where is the dictionary normalization work, for example?

**Comment by maximilianfanning** [comment]
I added the solution file to the code tab, and no other code is referenced directly. However, there is the letter data code that indirectly inputs data into this program. That is not likely to change in the near future, but would you like me to add the file anyway?

**Comment by michaelcfanning** [comment]
ok, so now you've added a new copy of your complete solution to the repo. Great! Now there are some extraneous files at the root that you should delete. To do this, please create a branch, delete those files, and create a pull request of the change. I will file a new issue for this, as you've closed this one!
